version: '3.8'

services:
  subsai-webui:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]

  subsai-webui-cpu:
    build:
      context: .
      dockerfile: Dockerfile